import type { Metadata } from "next";
import { Inter } from 'next/font/google'

import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Xash Monitor",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`h-screen w-screen fixed top-0 left-0 no-doc-scroll ${inter.className} text-header p-2 antialiased bg-background`}>{children}</body>
    </html>
  );
};

export default RootLayout;
